version: "3"
services:
  odin:
    image: mbround18/valheim-odin:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.odin
    volumes:
    - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: mbround18/valheim:latest
    restart: always
    environment:
      - PORT=2456
      - NAME="Pump_N_Sweat"
      - PASSWORD="${PASSWORD}"
      - TZ=America/Chicago
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./tmp/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./tmp/server:/home/steam/valheim
    - odin-output:/home/steam/.odin

volumes:
  odin-output:
