version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Pump_N_Sweat"
      - PASSWORD="${PASSWORD}"
      - TZ=America/Chicago
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 4 * * *"
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
